export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git fast-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Histoy in cache directory
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"

# Auto/tab completion
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vim='nvim'
alias vi='nvim'
alias cf='cd ~/.config'
alias zshrc='nvim ~/.zshrc'
alias zsh='nvim ~/.zshrc'
alias p='sudo pacman'
alias update='yay -Syu'
alias rr='cd ~/.local/src'

# Mozilla smooth scrolling
export MOZ_USE_XINPUT2=1

# Remap caps lock to escape, and increase rate
xset r rate 300 50
setxkbmap -option caps:super,alwin:menu_win
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
xset -q | grep -q 'Caps Lock:\s*on' && xdotool key Caps_Lock

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

source /usr/share/nvm/init-nvm.sh

# bun completions
[ -s "/home/andr/.bun/_bun" ] && source "/home/andr/.bun/_bun"

#bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

. "$HOME/.cargo/env"

# .local/bin scripts
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Start x
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then 
  exec startx &>/dev/null 
fi

